---
- name: Restart mysqld
  service: 
      name: mysqld
      state: restarted

- name: yum clean
  command: "{{item}}"
  loop:
      - "yum clean all"
      - "rm -rf /var/cache/yum"
  args:
      warn: no
